.TH "mainwindow.h" 3 "Sat Apr 2 2016" "InDivProvClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mainwindow.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QMainWindow>\fP
.br
\fC#include 'zmq\&.hpp'\fP
.br
\fC#include <json/json\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for InDivProvClient from the source code\&.
