.TH "mainwindow.cpp" 3 "Sat Apr 2 2016" "InDivProvClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mainwindow.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include 'ui_mainwindow\&.h'\fP
.br
\fC#include <boost/thread\&.hpp>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'zmq\&.hpp'\fP
.br
\fC#include <json/json\&.h>\fP
.br
\fC#include 'indiprovclient\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <boost/archive/text_oarchive\&.hpp>\fP
.br
\fC#include <boost/archive/text_iarchive\&.hpp>\fP
.br
\fC#include <boost/serialization/vector\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBmyteststruct\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for InDivProvClient from the source code\&.
