.TH "myteststruct" 3 "Sat Apr 2 2016" "InDivProvClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
myteststruct \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBz\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int myteststruct::x"

.SS "int myteststruct::y"

.SS "int myteststruct::z"


.SH "Author"
.PP 
Generated automatically by Doxygen for InDivProvClient from the source code\&.
