.TH "ProvUtils::WasDerivedFrom" 3 "Sat Apr 2 2016" "InDivProvClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProvUtils::WasDerivedFrom \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <provutils\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBgenEntID\fP"
.br
.ti -1c
.RI "string \fBusdEntID\fP"
.br
.ti -1c
.RI "string \fBactID\fP"
.br
.ti -1c
.RI "string \fBgenID\fP"
.br
.ti -1c
.RI "string \fBusgID\fP"
.br
.ti -1c
.RI "string \fBlabel\fP"
.br
.ti -1c
.RI "string \fBtype\fP"
.br
.ti -1c
.RI "string \fBID\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "string ProvUtils::WasDerivedFrom::actID"

.SS "string ProvUtils::WasDerivedFrom::genEntID"

.SS "string ProvUtils::WasDerivedFrom::genID"

.SS "string ProvUtils::WasDerivedFrom::ID"

.SS "string ProvUtils::WasDerivedFrom::label"

.SS "string ProvUtils::WasDerivedFrom::type"

.SS "string ProvUtils::WasDerivedFrom::usdEntID"

.SS "string ProvUtils::WasDerivedFrom::usgID"


.SH "Author"
.PP 
Generated automatically by Doxygen for InDivProvClient from the source code\&.
