.TH "ProvUtils::WasAssociatedWith" 3 "Sat Apr 2 2016" "InDivProvClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProvUtils::WasAssociatedWith \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <provutils\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBactID\fP"
.br
.ti -1c
.RI "string \fBagentID\fP"
.br
.ti -1c
.RI "string \fBplanID\fP"
.br
.ti -1c
.RI "string \fBlabel\fP"
.br
.ti -1c
.RI "string \fBrole\fP"
.br
.ti -1c
.RI "string \fBtype\fP"
.br
.ti -1c
.RI "string \fBID\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "string ProvUtils::WasAssociatedWith::actID"

.SS "string ProvUtils::WasAssociatedWith::agentID"

.SS "string ProvUtils::WasAssociatedWith::ID"

.SS "string ProvUtils::WasAssociatedWith::label"

.SS "string ProvUtils::WasAssociatedWith::planID"

.SS "string ProvUtils::WasAssociatedWith::role"

.SS "string ProvUtils::WasAssociatedWith::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for InDivProvClient from the source code\&.
