.TH "ProvUtils::Agent" 3 "Sat Apr 2 2016" "InDivProvClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProvUtils::Agent \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <provutils\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBlabel\fP"
.br
.ti -1c
.RI "string \fBlocation\fP"
.br
.ti -1c
.RI "string \fBtype\fP"
.br
.ti -1c
.RI "string \fBID\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "string ProvUtils::Agent::ID"

.SS "string ProvUtils::Agent::label"

.SS "string ProvUtils::Agent::location"

.SS "string ProvUtils::Agent::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for InDivProvClient from the source code\&.
