.TH "provutils.h" 3 "Sat Apr 2 2016" "InDivProvClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
provutils.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBProvUtils\fP"
.br
.ti -1c
.RI "struct \fBProvUtils::Entity\fP"
.br
.ti -1c
.RI "struct \fBProvUtils::Activity\fP"
.br
.ti -1c
.RI "struct \fBProvUtils::Agent\fP"
.br
.ti -1c
.RI "struct \fBProvUtils::Used\fP"
.br
.ti -1c
.RI "struct \fBProvUtils::WasGeneratedBy\fP"
.br
.ti -1c
.RI "struct \fBProvUtils::WasDerivedFrom\fP"
.br
.ti -1c
.RI "struct \fBProvUtils::WasAttributedTo\fP"
.br
.ti -1c
.RI "struct \fBProvUtils::WasAssociatedWith\fP"
.br
.ti -1c
.RI "struct \fBProvUtils::WasStartedBy\fP"
.br
.ti -1c
.RI "struct \fBProvUtils::WasEndedBy\fP"
.br
.ti -1c
.RI "struct \fBProvUtils::WasInformedBy\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for InDivProvClient from the source code\&.
