.TH "ProvUtils::WasStartedBy" 3 "Sat Apr 2 2016" "InDivProvClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProvUtils::WasStartedBy \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <provutils\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBactID\fP"
.br
.ti -1c
.RI "string \fBentID\fP"
.br
.ti -1c
.RI "string \fBstarterActID\fP"
.br
.ti -1c
.RI "string \fBsTime\fP"
.br
.ti -1c
.RI "string \fBlabel\fP"
.br
.ti -1c
.RI "string \fBlocation\fP"
.br
.ti -1c
.RI "string \fBrole\fP"
.br
.ti -1c
.RI "string \fBtype\fP"
.br
.ti -1c
.RI "string \fBID\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "string ProvUtils::WasStartedBy::actID"

.SS "string ProvUtils::WasStartedBy::entID"

.SS "string ProvUtils::WasStartedBy::ID"

.SS "string ProvUtils::WasStartedBy::label"

.SS "string ProvUtils::WasStartedBy::location"

.SS "string ProvUtils::WasStartedBy::role"

.SS "string ProvUtils::WasStartedBy::starterActID"

.SS "string ProvUtils::WasStartedBy::sTime"

.SS "string ProvUtils::WasStartedBy::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for InDivProvClient from the source code\&.
