.TH "ProvUtils::WasEndedBy" 3 "Sat Apr 2 2016" "InDivProvClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProvUtils::WasEndedBy \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <provutils\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBactID\fP"
.br
.ti -1c
.RI "string \fBentID\fP"
.br
.ti -1c
.RI "string \fBenderActID\fP"
.br
.ti -1c
.RI "string \fBeTime\fP"
.br
.ti -1c
.RI "string \fBlabel\fP"
.br
.ti -1c
.RI "string \fBlocation\fP"
.br
.ti -1c
.RI "string \fBrole\fP"
.br
.ti -1c
.RI "string \fBtype\fP"
.br
.ti -1c
.RI "string \fBID\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "string ProvUtils::WasEndedBy::actID"

.SS "string ProvUtils::WasEndedBy::enderActID"

.SS "string ProvUtils::WasEndedBy::entID"

.SS "string ProvUtils::WasEndedBy::eTime"

.SS "string ProvUtils::WasEndedBy::ID"

.SS "string ProvUtils::WasEndedBy::label"

.SS "string ProvUtils::WasEndedBy::location"

.SS "string ProvUtils::WasEndedBy::role"

.SS "string ProvUtils::WasEndedBy::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for InDivProvClient from the source code\&.
