.TH "ProvUtils::Used" 3 "Sat Apr 2 2016" "InDivProvClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProvUtils::Used \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <provutils\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBactID\fP"
.br
.ti -1c
.RI "string \fBentID\fP"
.br
.ti -1c
.RI "string \fBusedTime\fP"
.br
.ti -1c
.RI "string \fBlabel\fP"
.br
.ti -1c
.RI "string \fBlocation\fP"
.br
.ti -1c
.RI "string \fBrole\fP"
.br
.ti -1c
.RI "string \fBtype\fP"
.br
.ti -1c
.RI "string \fBID\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "string ProvUtils::Used::actID"

.SS "string ProvUtils::Used::entID"

.SS "string ProvUtils::Used::ID"

.SS "string ProvUtils::Used::label"

.SS "string ProvUtils::Used::location"

.SS "string ProvUtils::Used::role"

.SS "string ProvUtils::Used::type"

.SS "string ProvUtils::Used::usedTime"


.SH "Author"
.PP 
Generated automatically by Doxygen for InDivProvClient from the source code\&.
