.TH "ProvUtils::Entity" 3 "Sat Apr 2 2016" "InDivProvClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProvUtils::Entity \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <provutils\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBlabel\fP"
.br
.ti -1c
.RI "string \fBlocation\fP"
.br
.ti -1c
.RI "string \fBtype\fP"
.br
.ti -1c
.RI "string \fBvalue\fP"
.br
.ti -1c
.RI "string \fBID\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "string ProvUtils::Entity::ID"

.SS "string ProvUtils::Entity::label"

.SS "string ProvUtils::Entity::location"

.SS "string ProvUtils::Entity::type"

.SS "string ProvUtils::Entity::value"


.SH "Author"
.PP 
Generated automatically by Doxygen for InDivProvClient from the source code\&.
