.TH "ProvUtils::Activity" 3 "Sat Apr 2 2016" "InDivProvClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProvUtils::Activity \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <provutils\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBstartTime\fP"
.br
.ti -1c
.RI "string \fBendTime\fP"
.br
.ti -1c
.RI "string \fBlabel\fP"
.br
.ti -1c
.RI "string \fBlocation\fP"
.br
.ti -1c
.RI "string \fBtype\fP"
.br
.ti -1c
.RI "string \fBID\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "string ProvUtils::Activity::endTime"

.SS "string ProvUtils::Activity::ID"

.SS "string ProvUtils::Activity::label"

.SS "string ProvUtils::Activity::location"

.SS "string ProvUtils::Activity::startTime"

.SS "string ProvUtils::Activity::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for InDivProvClient from the source code\&.
