.TH "ProvUtils::WasAttributedTo" 3 "Sat Apr 2 2016" "InDivProvClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProvUtils::WasAttributedTo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <provutils\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBentID\fP"
.br
.ti -1c
.RI "string \fBagentID\fP"
.br
.ti -1c
.RI "string \fBlabel\fP"
.br
.ti -1c
.RI "string \fBtype\fP"
.br
.ti -1c
.RI "string \fBID\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "string ProvUtils::WasAttributedTo::agentID"

.SS "string ProvUtils::WasAttributedTo::entID"

.SS "string ProvUtils::WasAttributedTo::ID"

.SS "string ProvUtils::WasAttributedTo::label"

.SS "string ProvUtils::WasAttributedTo::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for InDivProvClient from the source code\&.
