.TH "ProvUtils" 3 "Sat Apr 2 2016" "InDivProvClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProvUtils \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <provutils\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBActivity\fP"
.br
.ti -1c
.RI "struct \fBAgent\fP"
.br
.ti -1c
.RI "struct \fBEntity\fP"
.br
.ti -1c
.RI "struct \fBUsed\fP"
.br
.ti -1c
.RI "struct \fBWasAssociatedWith\fP"
.br
.ti -1c
.RI "struct \fBWasAttributedTo\fP"
.br
.ti -1c
.RI "struct \fBWasDerivedFrom\fP"
.br
.ti -1c
.RI "struct \fBWasEndedBy\fP"
.br
.ti -1c
.RI "struct \fBWasGeneratedBy\fP"
.br
.ti -1c
.RI "struct \fBWasInformedBy\fP"
.br
.ti -1c
.RI "struct \fBWasStartedBy\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProvUtils\fP ()"
.br
.ti -1c
.RI "\fB~ProvUtils\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ProvUtils::ProvUtils ()"

.SS "ProvUtils::~ProvUtils ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for InDivProvClient from the source code\&.
